clip/urls.py
from django.urls import path, reverse_lazy
from .views import HomePage, HomeClips, DetailsClips, SearchClip, EditProfile, Register
from django.contrib.auth import views as auth_view


app_name = 'clip'

urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('clips/', HomeClips.as_view(), name='homeclips'),
    path('clips/<int:pk>/', DetailsClips.as_view(), name='detailsclips'),
    path('search/', SearchClip.as_view(), name='search'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html',
                                               success_url=reverse_lazy('clip:homeclips')), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/',  Register.as_view(), name='register'),
    path('editprofile/<int:pk>', EditProfile.as_view(), name='editprofile'),
    path('password-change/', auth_view.PasswordChangeView.as_view(template_name='editprofile.html',
                                                                 success_url=reverse_lazy('clip:homeclips') ), name='password_change'),
]  

clipflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clip.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clip/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.


LISTA_CATEGORIAS = (
    ('valorant', 'Valorant'),
    ('tarkov', 'Tarkov'),
    ('lol', 'League of Legends'),
    ('csgo', 'Cs:Go'),
    ('r6', 'Rainbow Six Siege'),
    ('desktop', 'Desktop'),

)

class Clip(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images')
    category = models.CharField(max_length=100, choices=LISTA_CATEGORIAS)
    created_at = models.DateTimeField(default=timezone.now)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class Episode(models.Model):
    title = models.CharField(max_length=100)
    video = models.URLField()
    clip = models.ForeignKey("Clip", related_name="episodes", on_delete=models.CASCADE)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    

class User(AbstractUser):
    clip_seen = models.ManyToManyField("Clip")

clip/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms

class RegisterFrom(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']



class HomeForm(forms.Form):
    email = forms.EmailField(label=False)

clip/views.py
from django.shortcuts import render, redirect, reverse
from .models import Clip, User, Episode
from .forms import RegisterFrom, HomeForm
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

class HomePage(FormView):
    template_name = 'index.html'
    form_class = HomeForm


    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
    
            return redirect('clip:homeclips')
        else:
            return super().get(request, *args, **kwargs)
        


    def get_success_url(self):
        email = self.request.POST.get('email')
        user = User.objects.filter(email=email)

        if user:
            return reverse('clip:login')
        else:
            return reverse('clip:register')
    


class HomeClips(LoginRequiredMixin, ListView):
    template_name = 'homeclips.html'
    model = Clip
 

class DetailsClips(LoginRequiredMixin, DetailView):
    template_name = 'detailsclips.html'
    model = Clip


    def get(self, request, *args, **kwargs):
        episode = self.get_object()
        episode.views += 1
        episode.save()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailsClips, self).get_context_data(**kwargs)


        return context
    

class SearchClip(LoginRequiredMixin, ListView):
    template_name = 'search.html'
    model = Clip

    def get_queryset(self):
        search_request = self.request.GET.get('q')
        if search_request:
            object_list = self.model.objects.filter(title__icontains=search_request)
            
            return object_list
       
        else:
            return None
       
   

class EditProfile(LoginRequiredMixin, UpdateView):
    template_name = 'editprofile.html'
    model = User
    fields = ['first_name', 'last_name' , 'email']


    def get_success_url(self):
        return reverse('clip:homeclips')


class Register(FormView):
    template_name = 'register.html'
    form_class = RegisterFrom

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


    def get_sucess_url(self):

        return reverse('clip:login')

clip/templates/detailsclips.html
{% extends "base.html" %} 
{% block title %} {{ object.title }} {% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.image.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                 {{ object.title }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.description|slice:":50" }}
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodes.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Description
            </h2>
            <div class="items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.description }}
                </p>
                <p class="text-gray-100 text-lg">
                    Visualizações: {{ object.views }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    All Clips

                </h2>
                    {% for clip in object.episodes.all %}
                    <h3 class='text-lg'>
                        <a href="{{ clip.video }}"><p>Clip: {{ clip.title }}</p></a>
                        </a>
                    </h3>
                    {% endfor %}

            </div>

        </div>
    </section>
</main>
{% endblock %}

clip/templates/editprofile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Edit Profile
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                  {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'clip:password_change' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>DevMasson</li>
        </ul>
    </footer>



{% endblock %}

clip/templates/homeclips.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ClipFlix{% endblock %}

{% block head %}
<style>
$itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;
    
    .item {
      padding: 0 2px;
      transition: $duration all;
      
      &:hover { 
        margin: 0 40px;
        transform: scale(1.2);
      }
      
    }
    
    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;
      
      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      
    }
    
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}


{% block content %}


<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{% static 'images/csgo.jpg' %}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{clip_primary.title}}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{clip_primary.description}}
            </p>
            <div class="flex my-4">
                <a href="#">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                {% for clip in list_recent_clips %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                    <a href="{% url 'clip:detailsclips' clip.pk %}">
                        <img src="{{ clip.image.url }}" class="rounded-md w-full h-full object-cover">
                    </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
              {% if list_recent_clips|length > 4 %}
                  <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                    {% for clip in list_recent_clips %}
                    {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'clip:detailsclips' clip.pk %}">
                            <img src="{{ clip.image.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                      </div>
                    {% endif %}
                    {% endfor %} 
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Popular
            </h2>
            <div class="wrapper">
              <section id="section1popular" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2popular" class="arrow__btn text-6xl page">‹</a>
                {% for clip in list_clip_popular %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                    <a href="{% url 'clip:detailsclips' clip.pk %}">
                        <img src="{{ clip.image.url }}" class="rounded-md w-full h-full object-cover">
                    </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2popular" class="arrow__btn text-6xl">›</a>
              </section>
              {% if list_clip_popular|length > 4 %}
                  <section id="section2popular" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1popular" class="arrow__btn text-6xl">‹</a>
                    {% for clip in list_clip_popular %}
                    {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'clip:detailsclips' clip.pk %}">
                            <img src="{{ clip.image.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                      </div>
                    {% endif %}
                    {% endfor %} 
                    <a href="#section1popular" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>


</main>
{% endblock %}

clip/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ClipFlix{% endblock %}

{% block head %}

<style>
    #id_email{
        width: 100%;
        color: #000000;
        padding: 5px 5px;
    }
</style>

{% endblock %}


{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Filmes e séries do Masson, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                    </a>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images\tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images\mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
        
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images\netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>DevMasson</li>
        </ul>
    </footer>
{% endblock %}

clip/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda? <p><a href="{% url 'clip:register' %}">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>DevMasson</li>
        </ul>
    </footer>
{% endblock %}

clip/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">   <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
       <h2 class="text-2xl">Você saiu da sua conta</h2>
       <div class="flex flex-nowrap justify-center space-x-5 p-5">
       <a href="{% url 'clip:login' %}"><button class="bg-red-600  py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>
       <a href="{% url 'clip:register' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>
       </div>
   </div>
</header>

<footer class=" px-5 py-10 ">
   <ul class="flex justify-between items-center">

       <li>&copy; 2021</li>
       <li> Feito com Python (Django)</li>
       <li>Hashtag</li>
   </ul>
</footer>
{% endblock %}

clip/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Register
{% endblock %}

{% block content %}

<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">

        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>DevMasson</li>
        </ul>
    </footer>

{% endblock %}

clip/templates/search.html
{% extends 'base.html' %}

{% block title %} Search {% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for clip in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'clip:detailsclips' clip.pk %}">
                          <img src="{{ clip.image.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

    {% block head %}
    {% endblock %}

</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
   
   <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-gray-900')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>


    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-5/12" src="{% static 'images\clipflix.png' %}">
        </a>

    </div>
    
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}    
        <div class="mr-2"> 
            <form method="get" action="{% url 'clip:search' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" value="{{ request.GET.query }}" name="q" placeholder="Search">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        
        <div class="mr-2">
            {% if user.is_authenticated %}
            <a href="{% url 'clip:logout' %} ">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Logout</button>
            </a>
            {% else %}
                <a href="{% url 'clip:login' %}">
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">Login</button>
                </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}    
        <div class="mr-2">
            <a href="{% url 'clip:editprofile' user.pk %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Edit Profile</button>
            </a>
        </div>
        {% else %}
        <div class="mr-2">
            <a href="#">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Register</button>
            </a>
        </div>
        {% endif %}

    </div>
    
</nav>